spring:
  datasource:
    url: jdbc:h2:mem:maindb
  jpa:
    hibernate:
      ddl-auto: validate      # схему создаёт Liquibase, Hibernate только проверяет
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml